#!/usr/bin/env python3

from subprocess import check_output, call
from os import environ
from re import match

color_muted = '#586e75'
color_normal = '#268bd2'#'#93a1a1'
glyphs = [ (50, ''), (20, ''), (0, '') ]
glyph_muted = ''
color = color_normal

default_step = 5

def get_volume():
    amixer_out = check_output(['amixer', 'sget', 'Master']).splitlines()
    for l in amixer_out:
        m = match(r'.* \d+ \[(\d+)%\] \[[+-]?\d+\.\d+dB\] \[(o(?:n|ff))\]',
                  str(l))
        if m:
            percentage = int(m.group(1))
            muted = m.group(2) == 'off'
            return percentage, muted

percentage, is_muted = get_volume()

for min_val, g in glyphs:
    if percentage >= min_val:
        glyph = g
        break

if is_muted:
    color = color_muted
    glyph = glyph_muted

block_button = environ.get('BLOCK_BUTTON', '')
if block_button:
    action = {
        '3' : 'toggle',
        '4' : '{}%+ unmute'.format(default_step),
        '5' : '{}%- unmute'.format(default_step),
    }.get(block_button, None)
    if action:
        call(['amixer', '-q', 'sset', 'Master'] + action.split())

print('{} {}%'.format(glyph, percentage))
print('{} {}%'.format(glyph, percentage))
if color:
    print(color)
