#!/usr/bin/env python3

from subprocess import check_output
from os import environ
from sys import exit
from re import search

color_down = '#586e75'
color_up = '#268bd2'
color = None
icon = ''

for l in check_output('nmcli --mode multiline c show --active'.split()).splitlines():
    k, v = l.split(b':')
    if k == b'NAME':
        name = v.strip()
        short_out = '{}  {}'.format(icon, name.decode('utf-8'))
        color = color_up
        break
else:
    short_out = ''

print(short_out)
print(short_out)

if color:
    print(color)
