# On windows this goes in %APPDATA%/alacritty/alacritty.toml
# Also on windows make a shortcut with these options:
# `-e wsl.exe --user gmoshkin --cd /home/gmoshkin`
# On linux this goes in ~/.alacritty.toml

[font]
size = 10

[[keyboard.bindings]]
mods = "Control"
key = "Space"
chars = "\u0000"

[[keyboard.bindings]]
mods = "Control"
key = "1"
chars = "1"

[[keyboard.bindings]]
mods = "Control"
key = "2"
chars = "\u0000"

[[keyboard.bindings]]
mods = "Control"
key = "3"
chars = "\u001b"

[[keyboard.bindings]]
mods = "Control"
key = "4"
chars = "\u001c"

[[keyboard.bindings]]
mods = "Control"
key = "5"
chars = "\u001d"

[[keyboard.bindings]]
mods = "Control"
key = "6"
chars = "\u001e"

[[keyboard.bindings]]
mods = "Control"
key = "7"
chars = "\u001f"

[[keyboard.bindings]]
mods = "Control"
key = "8"
chars = "\u007f"

[[keyboard.bindings]]
mods = "Control"
key = "9"
chars = "9"

[[keyboard.bindings]]
mods = "Control"
key = ";"
chars = ";"

[[keyboard.bindings]]
mods = "Control|Shift"
key = ":"
chars = ":"

[[keyboard.bindings]]
mods = "Control"
key = "."
chars = "."

[[keyboard.bindings]]
# Doesn't fucking work
mods = "Control|Shift"
key = "."
chars = ">"

[[keyboard.bindings]]
mods = "Control"
key = ","
chars = ","

[[keyboard.bindings]]
# Doesn't fucking work
mods = "Control|Shift"
key = ","
chars = "<"

[[keyboard.bindings]]
mods = "Control"
key = "/"
chars = "\u001f"

[[keyboard.bindings]]
# Doesn't fucking work
mods = "Control|Shift"
key = "/"
chars = "\u007f"
