# On windows this goes in %APPDATA%/alacritty/alacritty.toml
# Also on windows make a shortcut with these options:
# `-e wsl.exe --user gmoshkin --cd /home/gmoshkin`
# On linux this goes in ~/.alacritty.toml

# This is so stupid!!!
# Alacritty loads the main config (this file), so any settings inside it
# override every other loaded config file! This means that I have to do
# something like this if I want to have defaults with local overrides.
# Alternatively I could use the ~/.alacritty.toml file for local overrides and
# the deploy.sh script would simply create an empty file with just the import of
# the the default from dotfiles... But I'm not sure this is going to work on
# windows, so I'm going with this solution for now
[general]
import = [
    "~/dotfiles/alacritty-default.toml",
    "~/.alacritty-local.toml",
]

[[keyboard.bindings]]
mods = "Control"
key = "Space"
chars = "\u0000"

[[keyboard.bindings]]
mods = "Control"
key = "1"
chars = "1"

[[keyboard.bindings]]
mods = "Control"
key = "2"
chars = "\u0000"

[[keyboard.bindings]]
mods = "Control"
key = "3"
chars = "\u001b"

[[keyboard.bindings]]
mods = "Control"
key = "4"
chars = "\u001c"

[[keyboard.bindings]]
mods = "Control"
key = "5"
chars = "\u001d"

[[keyboard.bindings]]
mods = "Control"
key = "6"
chars = "\u001e"

[[keyboard.bindings]]
mods = "Control"
key = "7"
chars = "\u001f"

[[keyboard.bindings]]
mods = "Control"
key = "8"
chars = "\u007f"

[[keyboard.bindings]]
mods = "Control"
key = "9"
chars = "9"

[[keyboard.bindings]]
mods = "Control"
key = ";"
chars = ";"

[[keyboard.bindings]]
mods = "Control|Shift"
key = ":"
chars = ":"

[[keyboard.bindings]]
mods = "Control"
key = "."
chars = "."

[[keyboard.bindings]]
# Doesn't fucking work
mods = "Control|Shift"
key = "."
chars = ">"

[[keyboard.bindings]]
mods = "Control"
key = ","
chars = ","

[[keyboard.bindings]]
# Doesn't fucking work
mods = "Control|Shift"
key = ","
chars = "<"

[[keyboard.bindings]]
mods = "Control"
key = "/"
chars = "\u001f"

[[keyboard.bindings]]
# Doesn't fucking work
mods = "Control|Shift"
key = "/"
chars = "\u007f"

# MacOS command = alt
# TODO: maybe it's possible to actually have that behavior, or do I have to list
# out each individual key combo?

[[keyboard.bindings]]
mods = "Command"
key = "b"
chars = "\u001bb"

[[keyboard.bindings]]
mods = "Command"
key = "d"
chars = "\u001bd"

[[keyboard.bindings]]
mods = "Command"
key = "f"
chars = "\u001bf"

[[keyboard.bindings]]
mods = "Command"
key = "w"
chars = "\u001bw"

[[keyboard.bindings]]
mods = "Command"
key = "t"
chars = "\u001bt"

[[keyboard.bindings]]
mods = "Command"
key = "n"
chars = "\u001bt"

[[keyboard.bindings]]
mods = "Command"
key = "."
chars = "\u001b."
