alias pst='ps Tf'
alias psl='ps -A f | less'
alias lgrep='less-grep'
alias watch='watch --color -n 1'
alias cput='xsel --clipboard'
alias cget='cat | xsel --clipboard'
alias O='xdg-open'
alias gitstashpull='git stash && git pull && git stash pop'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias iperl6='jupyter-notebook --kernel=perl6'
alias df='df -h'
