[package]
name = "leetcode-4"
version = "0.1.0"
authors = ["Georgy Moshkin 00597037 <georgy.moshkin@huawei.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
