#!/usr/bin/env bash

source ~/dotfiles/tmux-powerlinerc

ERR=/tmp/cmus-remote.err

mode="$(cat /tmp/tmux-powerline_$USER/cmus_mode.txt 2>/dev/null)"
cmus_addr=${CMUS_ADDR:-${TMUX_POWERLINE_SEG_NOW_PLAYING_CMUS_REMOTE_HOST:-}}

if [ "$1" == volume ]; then
    COMMAND="~/dotfiles/scripts/volume.sh $2"
    case $mode in
        remote )
            if [ -n "$cmus_addr" ]; then
                ssh "$cmus_addr" "$COMMAND" 2> $ERR || echo cmus-remote: $(cat $ERR)
            else
                echo "cmus-remote: CMUS_ADDR is not set"
            fi
            ;;
        * )
            eval $COMMAND | bash 2> /dev/null
                echo "cmus-remote is not running"
            ;;
    esac
else
    if [ -n "$CMUS_PWD" ]; then
        cmus_remote="cmus-remote --server ${cmus_addr:-0.0.0.0} --passwd ${CMUS_PWD}"
    else
        cmus_remote="cmus-remote"
    fi
    if [ "$1" == add-to-playlist ]; then
        COMMAND="${cmus_remote} -C 'view 1' ;\
                 ${cmus_remote} -C 'win-sel-cur' ;\
                 ${cmus_remote} -C 'win-add-p'"
    else
        COMMAND="${cmus_remote} $@"
    fi
    eval $COMMAND | bash 2>&1
fi
